name: Build pull request

on:
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:
    inputs:
      BACKEND_ENV:
        default: ''
        description: 'Backend env for special features'
        required: false
      DEFI_SDK_API_URL:
        default: wss://api-v4.bwick.io/
        description: 'Bwick API'
        required: true
      DEFI_SDK_TESTNET_API_URL:
        default: wss://api-testnet.bwick.io/
        description: 'Bwick API Testnet'
        required: true
      BWICK_API_URL:
        default: https://zpi.bwick.io/
        description: 'Bwick REST API'
        required: true
      BWICK_TESTNET_API_URL:
        default: https://zpi-testnet.bwick.io/
        description: 'Bwick REST API'
        required: true
      PROXY_URL:
        default: https://proxy.bwick.io/
        description: 'Proxy API'
        required: true
      DEFI_SDK_TRANSACTIONS_API_URL:
        default: https://transactions.bwick.io
        description: 'Transaction Builder API'
        required: true
      PR_NUMBER:
        default: ''
        description: 'Pull request to attach the build to, e.g. 468'
        required: false

jobs:
  build_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        env:
          DEFI_SDK_API_URL: ${{ github.event.inputs.DEFI_SDK_API_URL || 'wss://api-v4.bwick.io/' }}
          DEFI_SDK_TESTNET_API_URL: ${{ github.event.inputs.DEFI_SDK_TESTNET_API_URL || 'wss://api-testnet.bwick.io/' }}
          BWICK_API_URL: ${{ github.event.inputs.BWICK_API_URL || 'https://zpi.bwick.io/' }}
          BWICK_TESTNET_API_URL: ${{ github.event.inputs.BWICK_TESTNET_API_URL || 'https://zpi-testnet.bwick.io/' }}
          BACKEND_ENV: ${{ github.event.inputs.BACKEND_ENV || '' }}
          PROXY_URL: ${{ github.event.inputs.PROXY_URL || 'https://proxy.bwick.io/' }}
          DEFI_SDK_TRANSACTIONS_API_URL: ${{ github.event.inputs.DEFI_SDK_TRANSACTIONS_API_URL || 'https://transactions.bwick.io' }}
          DEFI_SDK_API_TOKEN: Bwick.0JOY6zZTTw6yl5Cvz9sdmXc7d5AhzVMG
          TEST_WALLET_ADDRESS: ${{ secrets.TEST_WALLET_ADDRESS }}
          FEATURE_FOOTER_BUG_BUTTON: off
          MIXPANEL_TOKEN_PUBLIC: ${{ secrets.MIXPANEL_TOKEN_PUBLIC_DEV }}
          GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
          GOOGLE_ANALYTICS_API_SECRET: ${{ secrets.GOOGLE_ANALYTICS_API_SECRET }}
          STATSIG_API_KEY: ${{ secrets.STATSIG_API_KEY }}
          FEATURE_LOYALTY_FLOW: on
          FEATURE_BRIDGE_FORM: on
          FEATURE_SOLANA: on
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for gh-cli which is used in .github/scripts/
        run: |
          PR_NUMBER=${{ github.event.inputs.PR_NUMBER || github.event.number }}
          .github/scripts/set-env-from-pr-labels.sh "$PR_NUMBER"
          unset GH_TOKEN
          source $GITHUB_ENV
          npm install
          npm run build:production

      - name: Save PR number
        if: ${{ success() }}
        env:
          PR_NUMBER: ${{ github.event.inputs.PR_NUMBER || github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/

      - name: Compress build artifacts
        if: ${{ success() }}
        shell: bash
        run: |
          mv dist bwick-wallet-extension-${{github.sha}}
          zip -r bwick-wallet-extension-${{github.sha}}.zip bwick-wallet-extension-${{github.sha}}

      - name: Upload build
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: bwick-wallet-extension
          path: bwick-wallet-extension-${{github.sha}}.zip

      - name: Notify build succeeded
        id: notify-build-succeeded
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04JLLQRB43'
          payload: |
            {
              "text": ${{ toJSON(format('Build: {0}', github.event.pull_request.title)) }},
              "icon_emoji": ":nyancat:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(format('<{0}|{1}> {2}', github.event.pull_request.html_url, github.event.pull_request.title, github.pull_request.draft && ':construction:' || '')) }}
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Initiated by:* ${{ github.triggering_actor }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}

      - name: Notify build failed
        id: notify-build-failed
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04JLLQRB43'
          payload: |
            {
              "text": ${{ toJSON(format('Build: {0}', github.event.pull_request.title)) }},
              "icon_emoji": ":cry-cat:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(format('<{0}|{1}> {2}', github.event.pull_request.html_url, github.event.pull_request.title, github.pull_request.draft && ':construction:' || '')) }}
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Initiated by*: ${{ github.triggering_actor }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
